### ISSUE TITLE
Enter after scan a barcode.

### ISSUE THREAD

**Issue by dongchch2016** [ExLibrisGroup/SpineOMatic#12]
Hi,
When I input a barcode and click enter,then an error comes out.please check the attached.
![sc1](https://user-images.githubusercontent.com/24238286/87283641-13d03f80-c528-11ea-83e2-364d944ee090.jpg)
But the call number is still showing at the right place.

Thanks,
chenchen

**Comment by mgobat** [comment]
Looks like you are doing a "custom" label.  Could you please report the settings you have for the custom label?  They aren't completely visible in the screenshot.  Also, could you include the contents of the "Current XML" tab when this problem occurs?  Thank you.

**Comment by dongchch2016** [comment]
[currentXML.txt](https://github.com/ExLibrisGroup/SpineOMatic/files/4916126/currentXML.txt)
[customer.txt](https://github.com/ExLibrisGroup/SpineOMatic/files/4916127/customer.txt)
[spinelabel_settings.txt](https://github.com/ExLibrisGroup/SpineOMatic/files/4916128/spinelabel_settings.txt)

Hi,Mgobat,
please check,
thank you.
chenchen

**Comment by mgobat** [comment]
Chenchen...

I haven't been able to replicate the problem, but it looks like a font issue.  Could you try setting a barcode font on the "Print Setup" tab?  Your settings.som doesn't have one set.  If that doesn't help, try setting the text font to a font different than your current one, Microsoft Sans Serif.

**Comment by dongchch2016** [comment]
Hi,
I tried to set a barcode font with 'Microsoft Sans Serif Regular'. Cause I din't have Microsoft Sans Serif font in my laptop. But I found Microsoft Sans Serif Regular this one. But it still comes same error...

thank you.
![sc22](https://user-images.githubusercontent.com/24238286/87499832-b9e98a00-c68d-11ea-9758-dcfd98ebb724.jpg)
![sc11](https://user-images.githubusercontent.com/24238286/87499834-bb1ab700-c68d-11ea-8e7f-f27a27a253f6.jpg)

**Comment by mgobat** [comment]
Chenchen...are you using a Chinese localized version of Windows?

**Comment by dongchch2016** [comment]
Yes! Totally right!

**Comment by mgobat** [comment]
Would it be possible for you to install the Microsoft Sans Serif font to see if that resolves the problem?  I think you can download it if you search Google for "Microsoft Sans Serif font".

**Comment by dongchch2016** [comment]
Hi,
I have already installed the Microsoft Sans Serif font, but it didn't work. 
![sc](https://user-images.githubusercontent.com/24238286/87741119-4b840380-c816-11ea-8940-9750322883cb.jpg)
by the way, I'm not sure Microsoft Sans Serif and Microsoft Sans Serif Regular can  exist at the same time?

Thank you,
chenchen

**Comment by mgobat** [comment]
Hmmm....I thought adding the Microsoft Sans Serif font would solve the problem.   I believe the error you report is generated when setting the font during the formatting of the "Current XML" display.  And I think it is setting the font to an empty font object.  At least that was the only way I've been able to replicate the problem.

**Comment by mgobat** [comment]
Quick (and dirty) fix for next release, 8.1.  Chenchen...please install this new version; hopefully it will no longer generate the reported exception.

**Comment by dongchch2016** [comment]
All right.I'll try this version.
Thank you!

chenchen

**Comment by dongchch2016** [comment]
Hi  Mgobat,
Good news,It has been fixed!
Thank you for your patient and help!
chenchen
