### ISSUE TITLE
Is SpineOMatic Windows 10 compatible.

### ISSUE THREAD

**Issue by kellyaquinn** [ExLibrisGroup/SpineOMatic#13]
I noticed Windows 10 is not listed under Installation Requirements in this documentation below, and it is mentioned elsewhere that Windows 7 is preferred.

https://developers.exlibrisgroup.com/blog/spineomatic-label-printing-software-for-alma/

Is SpineOMatic compatible with Windows 10? Thanks!

**Comment by mgobat** [comment]
Yes, SpineOMatic is compatible with Windows 10.
