### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by DanieSwat** [ExLibrisGroup/SpineOMatic#14]
I followed the setup directions but when I scan a barcode I get a "Can't retrieve XML file. Error message: Illegal characters in path." error message.

Manually typed labels print fine.

**Comment by mgobat** [comment]
Could you please provide me with your "Alma URL" and "Method" values from the "Alma Access" tab?  You may email me at mark.gobat@exlibrisgroup.com.  Thank you.

**Comment by DanieSwat** [comment]
alma url: https://api-na.hosted.exlibrisgroup.com
method: /almaws/v1/items?view=label&item_barcode={item_barcode}
API key: l7xxfd3ec291dbb34f688306e8cfc964e490

**Comment by mgobat** [comment]
Let me look into this problem.  I deleted your comment because I didn't want your API key made public.  I received the necessary info though, thank you.

**Comment by mgobat** [comment]
Could you try testing using barcode 12345?  This one works for me.  Do you have a barcode that gives you the error?  What version of SpineOMatic are you running?

**Comment by DanieSwat** [comment]
Same error message with barcode "12345".

Version 8.1.0

**Comment by mgobat** [comment]
Try putting this URL in a web browser, replacing API_KEY_HERE with your real API key:
https://api-na.hosted.exlibrisgroup.com/almaws/v1/items?view=label&item_barcode=12345&apikey=API_KEY_HERE

Please let me know what you get back in your browser window.  
Thanks.

**Comment by DanieSwat** [comment]
I got " This XML file does not appear to have any style information
associated with it. The document tree is shown below." followed by a long
page of programese.

**Comment by mgobat** [comment]
Okay...that tells me that the problem isn't SpineOMatic.  Could you please email me the entire content of what displays in the web browser at mark.gobat@exlibrisgroup.com?  Thanks.

**Comment by mgobat** [comment]
The problem was a trailing blank at the end of the Alma URL on the "Alma Access" tab. Will open a bug specifically for that problem.
