### ISSUE TITLE
Can't Retrieve XML file

### ISSUE THREAD

**Issue by jpl-systems** [ExLibrisGroup/SpineOMatic#21]
I"m getting this error message:
***** ERROR ***** 
Can't retrieve XML file.
Error message: The underlying connection was closed: An unexpected error occurred on a receive.

It was working fine on Friday but when the staff came back on Monday Feb 8th 2021, all staff are getting this error message.  I tested the API key and it is working.  I tested by pasting the link( https://api-na.hosted.exlibrisgroup.com/almaws/v1/items?view=label&apikey=xxxxxxxxx&item_barcode=30750024760310)  with barcodes and APIkey to Chrome and did get the XML.

![SPINEOMatic error](https://user-images.githubusercontent.com/51174588/107318840-879ce100-6a52-11eb-9e6d-516abd17aa38.JPG)

I'm not sure if others getting the same problem.

**Comment by mgobat** [comment]
Customer reported that disabling TLS 1.0 caused the problem.  Campus requires that TLS be disabled.  After upgrading to SpineOMatic 8.0, the customer no longer had the problem with TLS 1.0 disabled.
