### ISSUE TITLE
Allow user to limit # of characters to 10 or more

### ISSUE THREAD

**Issue by ohsospoko** [ExLibrisGroup/SpineOMatic#23]
I was excited to see the new feature in 8.1.0 allowing the user to limit the number of characters from a field. Sadly, the field I'm trying to limit is a date, so I need 10 characters from it ('YYYY-MM-DD'). When I put "10" before the field name, it gets read as a "1". I can limit to 9 characters, which is frustratingly close to what I need. Any way to get that 10th character?

**Comment by mgobat** [comment]
Nice to see someone using this new feature!  Its original intent was to limit the number of characters from1 to 9.  I see that this is too limiting for your needs.  So, its kind of a bug, kind of an enhancement.  Let me see what I can do.

**Comment by mgobat** [comment]
Added code to support specifying more than 9 characters to include for an element.  In next release.
