### ISSUE TITLE
Question - minimum privileges for API key and CloudApp

### ISSUE THREAD

**Issue by danizen** [ExLibrisGroup/SpineOMatic#24]
Hi,

I've just let one of my technical librarians know that there is both a SpineOMatic application and a cloud app.  She was clearly trying to use the application, and I am wondering whether you guys are still supporting the application and what your plans on as to how long you plan to do so.

Also, if we do want to setup the application, what API privileges does the API key need?

Thanks,

Dan Davis
National Library of Medicine

**Comment by mgobat** [comment]
Hi Dan...

We just released a new version of the SpineOMatic application on 04-March-2021.  There is no plan to discontinue support for the application.  I imagine as the Cloud App version is enhanced with functionality, its use will increase, and we may re-evaluate over time.

You need an API key with read-access to Bibliographic records for the SpineOMatic application.

-mark

**Comment by danizen** [comment]
Thanks - the implementation team has decided to use it.
