### ISSUE TITLE
Update Spineomatic

### ISSUE THREAD

**Issue by rodltl** [ExLibrisGroup/SpineOMatic#26]
Good afternoon everyone,

I have spineomatic 7.0 at my workplace and the API may break soon so I need to update it.  Unfortunately, the check for update functionality is not working.  Is there an easy way to upgrade what we currently have so I do not need to reconfigure this software?  It was installed before I started this position so I'm completely unfamiliar with it.  Thank you in advance.

**Comment by mgobat** [comment]
To be safe, you can make a copy of the settings.som file in the folder in which the SpineOMatic program resides.  But the installation of a newer version is just copying a binary file.  You may download the latest version from https://github.com/ExLibrisGroup/SpineOMatic/releases.  It shouldn't affect your settings.

**Comment by rodltl** [comment]
I expected this to be much worse.  I have already upgraded the programs and want to thank you for your assistance.  You saved me a lot of time and effort. Have a great weekend.
