### ISSUE TITLE
Print is overextending

### ISSUE THREAD

**Issue by matthewdineiro** [ExLibrisGroup/SpineOMatic#31]
Hi, I'm printing spine labels, and it's having the issue where it prints out one correct label and then overextends a few labels after that. It seems like it thinks it's a full 8.5x11 page rather than the small label it's printing out. I also don't know if the fact that the label printer is an old Dot Matrix printer affects this problem.

**Comment by mitchellkocken** [comment]
Any update for this? Having exact same issue after updating to Windows 11

**Comment by mgobat** [comment]
Closed due to lack of response.
