### ISSUE TITLE
Label printer compatibility

### ISSUE THREAD

**Issue by bmulchin** [ExLibrisGroup/SpineOMatic#34]
Hello,
Would it be possible to get confirmation whether a TSC TTP-247 thermal label printer is compatible with SpineOMatic? I'm trying to use one in Alma, but after getting SpineOMatic installed and the API set up, I hit print and nothing happens. I'm wondering if it's a compatibility issue or if I don't have all of the drivers I need for the printer (it was difficult to get it working with our previous ILS).

Thank you,
Ben
University of La Verne

**Comment by mgobat** [comment]
@bmulchin, SpineOMatic doesn't explicitly support or not support any particular printer. The program relies on the existence of a Windows printer driver for the printer. The SpineOMatic program itself doesn't do anything special for any one printer. I would ensure you have the latest version of the Windows printer driver for the TSC TTP-247 installed, then give SpineOMatic a try.

**Comment by bmulchin** [comment]
I see, thank you. I'll do some more digging and make sure I have all of the drivers I need for my printer.
