### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by JaynaLG** [ExLibrisGroup/SpineOMatic#36]
I am experiencing "Error Message 401: the remote server returned an error: after I configured Spine-O-Matic. 
Our library only has 1 Zebra printer and I downloaded the Spine-O-Matic software within my user profile on workstation that already has the software downloaded but is only accessible on another profile. 
Please advise.

**Comment by mgobat** [comment]
Hi @JaynaLG. Did you get beyond this problem? If not. help me understand the problem a bit better. You've installed SpineOMatic on the same workstation twice, each time as a different user....but only one of them works correctly even though both copies are configured identically? Thanks.

**Comment by mgobat** [comment]
Closing due to lack of response. Please open a new issue if this problem continues.
