### ISSUE TITLE
Printing local call numbers.

### ISSUE THREAD

**Issue by risard** [ExLibrisGroup/SpineOMatic#37]
Hi, 

We're new to SpineOMatic at my library having just migrated to Alma, and I can't seem to figure out how to print a local call number. We have a number of books in a "Leisure Collection" with custom call numbers in the 090 field. However, The XML SpineOMatic is pulling from Alma, only pulls the 050. Is there a way to include the 090?

Thanks
Robin

**Comment by mgobat** [comment]
@risard, please see [this ExLibris Developer Network Page](https://developers.exlibrisgroup.com/alma/apis/docs/bibs/R0VUIC9hbG1hd3MvdjEvYmlicy97bW1zX2lkfS9ob2xkaW5ncy97aG9sZGluZ19pZH0vaXRlbXMve2l0ZW1fcGlkfQ==/) for details of what item information is returned to SpineOMatic from Alma for inclusion in your printed labels. The contents of the response is not modifiable.
