### ISSUE TITLE
can't print barcode with flag slips

### ISSUE THREAD

**Issue by samigholam** [ExLibrisGroup/SpineOMatic#38]
When printing custom flag slips there is an option to print the barcode !<barcode>
in the printer setup I select the barcode font "Free 3 of 9 Extended" this is the font that most libraries use
but the label preview of the barcode is not translated into a barcode !39585739309
any idea how to fix this? - thanks
![no barcode](https://user-images.githubusercontent.com/33610102/148325805-879e3830-1bc8-4481-a586-778445f61f92.jpg)
![Barcodefont](https://user-images.githubusercontent.com/33610102/148325822-c81c2ca2-6a8c-400b-87f8-cf5eaf34f9d0.jpg)

**Comment by mgobat** [comment]
Does the printed label contain the translated barcode? I believe "Preview" doesn't display the translated barcode regardless of font selection.

**Comment by samigholam** [comment]
Thanks for the response, the barcode prints on a laser printer, my confusion was that in the documentation the barcode was showing in the yellow box but that might be for demo purpose. - thanks

**Comment by cneal111** [comment]
@samigholam Hello, I was wondering if you experienced an issue with the 1D (scannable) barcode printing twice?
