### ISSUE TITLE
Custom labels fail when an XML element does not exist

### ISSUE THREAD

**Issue by Otterfan** [ExLibrisGroup/SpineOMatic#4]
### Current behavior

Custom labels fail if the elements required to build that label don't exist. For example, a label like

    <title>
    <author>

Will fail if the item does not have an `<author>`, which is not uncommon. 

### Expected behavior

Either of the following:

- Missing elements should not trigger an error at all.
- Missing elements should trigger an error that can be suppressed if the field is prefixed with the asterisk (`*`) operator. The asterisk currently suppresses elements only if the element is blank but not if it is not present.

**Comment by mgobat** [comment]
Repaired for next release:   if the field is prefixed with the asterisk (*) operator and the field is missing, the error is suppressed.  Existing asterisk (*) operator functionality maintained.
