### ISSUE TITLE
Call Number Type 5 not currently handled?

### ISSUE THREAD

**Issue by dancromwell** [ExLibrisGroup/SpineOMatic#51]
At one of the libraries in our consortium a call number type 5 is used for a particular location.  A user from this institution has reported an error using the SpineOMatic PC App for holdings marked with this type.   Is there a way to get call number type 5 handled with the PC app that I'm just not seeing?  It seems that "Other" handles 4, 7 and 8.  Five denotes a Title is used but I don't see a choice to select this type of entry.  I'm not sure if there are true titles so if 5 is not handled should I just suggest that the indicator be globally updated to something else as the solution?

Daniel Cromwell

**Comment by mgobat** [comment]
@dancromwell, what are the values for the fields on the "Call Number Format" tab in SpineOMatic? Is the "Ex Libris parsing" radio button selected with "<parsed_call_number>" set as the field to use? If the call number type is mapped to parsing routine 5 in Alma (https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/Physical_Resource_Management/070_Configuring_Resource_Management/060_Configuring_Call_Number_Parsing_when_Printing_Labels), the <parsed_call_number> element should contain what they are after. 

After scanning the barcode in SpineOMatic, you can look at the value Alma returned by clicking the "Current XML" tab and looking for the <parsed_call_number> element.

**Comment by dancromwell** [comment]
@mgobat here is an image of the Current XML

![irsc-call-number-printing](https://user-images.githubusercontent.com/75325765/190492923-6a9ceb51-b1fd-471b-93cb-f4ffee65e048.png)

**Comment by mgobat** [comment]
@dancromwell, I'm puzzled by this behavior. In the XML example you provided above, you should just see
```
KID
TOO 
```
as the call number on the label if the "Ex Libris parsing" radio button is selected and the <parsed_call_number> field is specified. It should be printing the call number as defined/parsed by Alma. These settings will give you the "Call# Parser: Ex Libris" text right below the scanned in call number.

I believe the "Call number type 5 is not handled by any parsing routine." message should only appear if you have the "SpineOMatic parsing" radio button selected and an XML element specified, for example <call_number>. If the "SpineOmatic parsing" radio button is selected, then the settings that appear when you click "Tweak and Test" are used to parse the call number. You can specify on each of the tabs which call number types should be handled by those particular settings. Since you are seeing "Call number type 5 is not handled...", then 5 is not included in any of the "Handles Call Number Type(s)" fields on the "Tweak and Test" tabs. Does that make sense?

**Comment by dancromwell** [comment]
@mgobat on the "Call Number Format" tab in the SpineOMatic settings the "Ex Libris parsing" radio button is selected.   I do see there is a button for "Tweak $ Test" but this perhaps is only relevant to when "SpineOMatic parsing is selected, no?   I mention this because the 5 is indeed not handled by any of the call number types here and so I wonder if that is related to the message regarding not handling type 5 even while having selected Ex Libris parsing.   

I was told that the handling error message is not given for call number type 4 like it is for type 5 but that type 4 was also not being displayed in the preview and can't be successfully printed either.   One thing that I have noticed is that $k is used by this school with both type 4 and 5 and that the XML for the <parsed_cal_number" data has <call_no_1> blank.  I'm pulling at straws but wonder if the $k in the call number data is playing a role in the issues they are having.  When the type is 0 and there is not $k the $h data starts in <call_no_1> in contrast to 4 and 5 with $k starting in <call_no_2>.  Perhaps a wild goose chase but...

**Comment by dancromwell** [comment]
@mgobat here is an image of the Alma parsing table and Title is included which I would expect to be associated with 1st indicator 5: 
![irsc_call_no_parsing_table](https://user-images.githubusercontent.com/75325765/191362482-0a40959a-8d40-475d-aa32-84f1e547b3d7.png)

**Comment by dancromwell** [comment]
@mgobat I am guessing you have a lot of other pressing work.  Just wondering if you had a chance to look into this anymore.  Thanks.

**Comment by dancromwell** [comment]
@mgobat OK, I understand.  My user is ust still puzzled about her use of the indicators 4 and 5 and the error message in SpineOMtic given we should be using Alma parsing per our setup of the mapping table.

**Comment by mgobat** [comment]
@dancromwell, let me confirm a few things. It's basically a summary of previous comments:

1. You have the "Ex Libris parsing" radio button selected with <parsed_call_number> as the source file.
2. Call number types 4 and 5 are NOT configured on any of the call number tabs on the "Tweak & Test" panel.
3. Scanning in a barcode for an item with call number type 4 does NOT produce a "Call number type 4 is not handled by any parsing routine." message box.
4. Scanning in a barcode for an item with call number type 5 DOES produce a "Call number type 5 is not handled by any parsing routine" message box.

Assumptions, I'd like confirmed:

1. In the case of call number type 4, nothing prints in the preview box.
2. In the case of call number type 5, "Unhandled Call Number Type" appears in the preview box.

What happens if you add call number types 4 and 5 to one of the call number tabs on the "Tweak & Test" panel", but still have the "Ex Libris parsing" radio button selected when you scan in a barcode?

Thanks...

-mark


Also, the image you provided earlier for the call number type 5 appears to just be a subset of the XML actually returned, as there is no <call_number_type> element in the image. Could you provide the full XML for the call number type 5 test case, too?

Thank you.

**Comment by dancromwell** [comment]
@***@***.***>,

Here are my replies to the summary and assumptions:


  1.  You have the "Ex Libris parsing" radio button selected with <parsed_call_number> as the source file. [dec - Yes]
  2.  Call number types 4 and 5 are NOT configured on any of the call number tabs on the "Tweak & Test" panel. [dec - 4 is but 5 is not]
  3.  Scanning in a barcode for an item with call number type 4 does NOT produce a "Call number type 4 is not handled by any parsing routine." message box. [dec - Yes, there is no message, but nothing displays in preview in SpineOMatic.]
  4.  Scanning in a barcode for an item with call number type 5 DOES produce a "Call number type 5 is not handled by any parsing routine" message box. [dec - Yes]

Assumptions, I'd like confirmed:

  1.  In the case of call number type 4, nothing prints in the preview box. [dec - correct, nothing displays in preview area, only the title is shown in the top of the above the barcode box]
  2.  In the case of call number type 5, "Unhandled Call Number Type" appears in the preview box. [dec - nothing displays in the preview area, but a pop-up window comes up immediately after I hit return after pasting in the barcode.  After clicking the "OK" in the pop-up message the title appears over the barcode box in SpineOMatic.]
***@***.***


What happens if you add call number types 4 and 5 to one of the call number tabs on the "Tweak & Test" panel", but still have the "Ex Libris parsing" radio button selected when you scan in a barcode? [dec - I added 5 to the "Other" pane and now it behaves the same as 4, basically no preview but also no pop-up with message.]


Also, the image you provided earlier for the call number type 5 appears to just be a subset of the XML actually returned, as there is no <call_number_type> element in the image. Could you provide the full XML for the call number type 5 test case, too?


<?xml version="1.0" ?>
<printout>
<result>
<error> </error> </result>
<form-name>Default</form-name>
<form-language>???</form-language>
<form-format>??</form-format>
<section-01>
<physical_item_display_for_printing>
<mms_id>9938187045906579</mms_id>
<bib_suppress_from_publishing>false</bib_suppress_from_publishing>
<title>The tooth book /</title>
<author>LeSieg, Theo.,</author>
<isbn>9780375824920</isbn>
<complete_edition>1st Random House bright and early board book ed.</complete_edition>
<network_numbers>
<network_number>(OCoLC)52585719</network_number>
<network_number>(Aleph)001432586FCC01</network_number>
<network_number>(EXLNZ-01FALSC_NETWORK)9912655855506561</network_number> </network_numbers>
<place_of_publication>New York :</place_of_publication>
<date_of_publication>2003, c1981.</date_of_publication>
<publisher_const>Random House</publisher_const>
<holding_id>2251099350006579</holding_id>
<holding_suppress_from_publishing>false</holding_suppress_from_publishing>
<permanent_call_number_type_name>Title</permanent_call_number_type_name>
<permanent_call_number_type>5</permanent_call_number_type>
<permanent_call_number>KID TOO</permanent_call_number>
<call_number_type_name>Title</call_number_type_name>
<call_number_type>5</call_number_type>
<call_number>KID TOO</call_number>
<accession_number> </accession_number>
<copy_id> </copy_id>
<in_temp_location>false</in_temp_location>
<temp_call_number_type> </temp_call_number_type>
<temp_call_number> </temp_call_number>
<temp_call_number_source> </temp_call_number_source>
<temp_policy> </temp_policy>
<pid>2351099330006579</pid>
<barcode>34201011615782</barcode>
<creation_date>2022-09-06Z</creation_date>
<modification_date>2022-09-05Z</modification_date>
<base_status_name>Item in place</base_status_name>
<base_status_code>1</base_status_code>
<awaiting_reshelving>false</awaiting_reshelving>
<physical_material_type_name>Book</physical_material_type_name>
<physical_material_type_code>BOOK</physical_material_type_code>
<policy_name>12 Regular Loan/ NonRequest</policy_name>
<policy_code>12</policy_code>
<provenance> </provenance>
<po_line> </po_line>
<arrival_date>2022-09-06Z</arrival_date>
<year_of_issue> </year_of_issue>
<enum_a> </enum_a>
<enum_b> </enum_b>
<enum_c> </enum_c>
<enum_d> </enum_d>
<enum_e> </enum_e>
<enum_f> </enum_f>
<enum_g> </enum_g>
<enum_h> </enum_h>
<chron_i> </chron_i>
<chron_j> </chron_j>
<chron_k> </chron_k>
<chron_l> </chron_l>
<chron_m> </chron_m>
<break_indicator> </break_indicator>
<pattern_type> </pattern_type>
<linking_number> </linking_number>
<type_of_unit> </type_of_unit>
<issue_level_description> </issue_level_description>
<replacement_cost>4.99</replacement_cost>
<receiving_operator>75974</receiving_operator>
<process_type> </process_type>
<inventory_number> </inventory_number>
<inventory_price> </inventory_price>
<library_name>Indian River/Ft. Pierce</library_name>
<library_code>IRCFO</library_code>
<location_name>Kids' Books</location_name>
<location_code>KID</location_code>
<alternative_call_number> </alternative_call_number>
<alternative_call_number_type> </alternative_call_number_type>
<storage_location_id> </storage_location_id>
<pages> </pages>
<pieces> </pieces>
<public_note> </public_note>
<fulfillment_note> </fulfillment_note>
<internal_note_1> </internal_note_1>
<internal_note_2> </internal_note_2>
<internal_note_3> </internal_note_3>
<statistics_note_1> </statistics_note_1>
<statistics_note_2> </statistics_note_2>
<statistics_note_3> </statistics_note_3>
<requested>false</requested>
<edition>1st Random House bright and early board book ed.</edition>
<imprint>New York : Random House, 2003, c1981.</imprint>
<language>eng</language>
<library_details>
<address>
<line1>Indian River State College</line1>
<line2>Miley Library on the Massey Campus</line2>
<line3>3209 Virginia Avenue</line3>
<line4> </line4>
<line5> </line5>
<city>Fort Pierce</city>
<country> </country>
***@***.******@***.***%3c/email>>
<phone>772-462-7600</phone>
<postal_code>34981-5599</postal_code>
<state>FL</state> </address> </library_details>
<parsed_call_number>
<call_no_1> </call_no_1>
<call_no_2>KID</call_no_2>
<call_no_3>TOO</call_no_3> </parsed_call_number>
<title_abcnph>The tooth book / by Dr. Seuss writing as Theo. LeSieg ; illustrated by Joe Mathieu.</title_abcnph>
<retention_reason> </retention_reason>
<retention_note> </retention_note>
<current_date>10/28/2022</current_date> </physical_item_display_for_printing> </section-01> </printout>


Daniel Cromwell
Systems Specialist Technical Services
Library Services
Florida Virtual Campus (FLVC)
Email: ***@***.******@***.***>

**Comment by mgobat** [comment]
@dancromwell, its looking like the problem is the empty <call_no_1>. Is there ever a case where you'd have another part of the call number empty? For example, would you ever have values in <call_no_1> and <call_no_3>, but not <call_no_2>? The current code stops processing the call number when it finds an empty "part", hence why you get nothing on the label when <call_no_1> is empty.

**Comment by mgobat** [comment]
@dancromwell, is this still an issue?  Thanks.

**Comment by dancromwell** [comment]
@mgobat I'm sorry.  I must have missed your previous message.  While I have not communicated with the local person here who first reported the problem in a while, I'm sure she still would like a resolution.   Let me investigate your question regarding empty parts of the call number.  I will need to look at some of the local data for the user's institution.

Daniel

**Comment by dancromwell** [comment]
@mgobat I'm not totally sure I understand what determines the parts such as call_no_1, call_no_2, and call_no_3.   The holding record that contains the call number in this case has an 852 that looks like this:

852 5_ |a FFpl |b IRCFO |c KID |h TOO |k KID

The parsing routine is 3 in Alma which says:

Split by a space:

Splits the call number at spaces and subfield i.
If the character ^ is present in the call number, it is converted to a space but does not break at that point.
Example:
Call number = $$hG635.H4$$iA3 1989^a
Label printed:

G635.H4
A3
1989 a

-------

In the 852 I do notice that the call number consists of $h and $k where $k is the prefix and is being placed before $h but in the XML it is put into call_no_2 instead of call_no_1:

<call_no_1> </call_no_1>
<call_no_2>KID</call_no_2>
<call_no_3>TOO</call_no_3>

Daniel

**Comment by dancromwell** [comment]
@mgobat I just tested by modifying the 852 in the holding record in Alma to be:

852 5_ |a FFpl |b IRCFO |c KID |h KID |i TOO

That is put the prefix in subfield h and the call number in subfield i.

The label is successfully generated.   So it looks like change the way the call number is entered is a possible solution. 

Daniel

**Comment by mgobat** [comment]
@dancromwell, can you confirm with your user that the change in call number entry is acceptable? Thank you.

**Comment by dancromwell** [comment]
@mgobat yes, I will check with the user.  I also put in a support case with Ex Libris to check and see if there is any chance that when the prefix subfield k is present if they could place it in call_no_1 with the rest of the call number as entered placed in the following call number tags in the XML.  I have not gotten an answer yet.

Daniel
