### ISSUE TITLE
Printable entries does not match printed lable 

### ISSUE THREAD

**Issue by shaw-spence** [ExLibrisGroup/SpineOMatic#52]
After scanning in all items to batch print on the printer, the number of entries (in first image 61 entries listed) do not all show up in the print preview or in the final printed page. No option to adjust number of printed entries, please advise. 
![image](https://user-images.githubusercontent.com/114608270/192847797-02443a87-c439-4dd8-b240-f1dfa0d06da4.png)
(image of Spinomatic 8.1.2 after all entries have been scanned, shows 61 entries)
![image](https://user-images.githubusercontent.com/114608270/192848301-0805be9e-4e19-4097-b025-2828b2dcb625.png)
(image of Print Preview window shows only 34 of the 61 entries.)

**Comment by mgobat** [comment]
@shaw-spence, what happens if you scan in a single barcode, then change the number of labels to print to 61 before clicking the "Add to batch #1" button? Are all 61 in the preview and in the printed label set?

**Comment by shaw-spence** [comment]
From what I remember from this issue was one of the books i scanned didn't have a call number field. When I scanned that book, it derailed the rest of the books that followed. It hadn't happened previously and hasn't happened since then. I still don't understand what triggered the problem.

**Comment by mgobat** [comment]
@shaw-spence, thanks for the update. I'll close this issue; we can reopen if it happens again.
