### ISSUE TITLE
Blank Labels Between Prints

### ISSUE THREAD

**Issue by PamClark** [ExLibrisGroup/SpineOMatic#53]
When I print a second label, it leaves 3 blank labels between the first and second print job. How can I resolve this? Please help.

**Comment by mgobat** [comment]
@PamClark, just to confirm; this is with the SpineOMatic Windows application and not the SpineOMatic Cloud App? We have a similar report in the Cloud App and want to ensure your issue is with the Windows app. Thanks.

**Comment by PamClark** [comment]
Yes, it was the SpineOMatic Windows app. Another one of our IT people came over and figured out that the problem was in the label size setting. For some reason when I got a new computer, and SpineOMatic was reinstalled, we didn't get that setting set to our specifications. Thank you so much for checking on this issue!

**Comment by mgobat** [comment]
@PamClark, glad you were able to resolve the problem!
