### ISSUE TITLE
Label Prefixes

### ISSUE THREAD

**Issue by dncal213** [ExLibrisGroup/SpineOMatic#59]
How do I use the label prefix? I have created my list using the formula library name + location name=Label Text but how do I apply it? Looking for instruction but have yet to find them.
Thank you.

**Comment by mgobat** [comment]
@dncal213, assuming you are asking about the SpineOMatic Windows application rather than the Alma Cloud App, once you have set up the label prefixes, they should automatically start appearing in your labels. Ensure that the fields specified for the "Library source" and "Location source" on the "Label Prefixes" tab are in the XML displayed on the "Current XML" tab after scanning in a barcode.

If you are speaking of the Alma Cloud App version, you must include the "Label Prefix" field in your template configuration. It is included in the "Add field" dropdown when editing the template "Label contents".

**Comment by dncal213** [comment]
Hello,
I am speaking about the application. I have not been successful.

**Comment by dncal213** [comment]
I am not sure the configuration is correct
[cid:8bbd902a-0689-4033-b7fc-bed23ba3a3b1]

Host Name: dnava-laptop; IP Address: fe80::67bb:b704:c0c4:157%8
6/19/2023 12:22:49 PM

<?xml version="1.0" ?>
<printout>
<result>
<error> </error> </result>
<form-name>Default</form-name>
<form-language>???</form-language>
<form-format>??</form-format>
<section-01>
<physical_item_display_for_printing>
<mms_id>991000522949703731</mms_id>
<bib_suppress_from_publishing>false</bib_suppress_from_publishing>
<title>Key population and vital statistics.</title>
<author>Great Britain. Office of Population Censuses and Surveys.</author>
<issn>1469-2732</issn>
<complete_edition> </complete_edition>
<network_numbers>
<network_number>(OCoLC)17887866</network_number> </network_numbers>
<place_of_publication>London :</place_of_publication>
<date_of_publication>1988-</date_of_publication>
<publisher_const>HMSO</publisher_const>
<holding_id>22510248000003731</holding_id>
<holding_suppress_from_publishing>false</holding_suppress_from_publishing>
<calculated_suppress_from_publishing>false</calculated_suppress_from_publishing>
<permanent_call_number_type_name>Library of Congress classification</permanent_call_number_type_name>
<permanent_call_number_type>0</permanent_call_number_type>
<permanent_call_number>HA1123 .L625</permanent_call_number>
<call_number_type_name>Library of Congress classification</call_number_type_name>
<call_number_type>0</call_number_type>
<call_number>HA1123 .L625</call_number>
<accession_number> </accession_number>
<copy_id>1</copy_id>
<in_temp_location>false</in_temp_location>
<temp_library_name>Library for International and Public Affairs</temp_library_name>
<temp_library_code>VKC</temp_library_code>
<temp_location_name>NEW-BOOKS</temp_location_name>
<temp_location_code>vkc-newbks</temp_location_code>
<temp_call_number_type> </temp_call_number_type>
<temp_call_number> </temp_call_number>
<temp_call_number_source> </temp_call_number_source>
<temp_policy> </temp_policy>
<pid>231274680780003731</pid>
<barcode>31275058410417</barcode>
<creation_date>2023-06-07Z</creation_date>
<modification_date>2023-06-06Z</modification_date>
<base_status_name>Item not in place</base_status_name>
<base_status_code>0</base_status_code>
<awaiting_reshelving>false</awaiting_reshelving>
<physical_material_type_name>Issue</physical_material_type_name>
<physical_material_type_code>ISSUE</physical_material_type_code>
<policy_name>4-WEEK</policy_name>
<policy_code>4-WEEK</policy_code>
<provenance> </provenance>
<po_line>93-S13139_2017_2</po_line>
<is_magnetic>false</is_magnetic>
<arrival_date>2023-06-07Z</arrival_date>
<year_of_issue> </year_of_issue>
<enum_a> </enum_a>
<enum_b> </enum_b>
<enum_c> </enum_c>
<enum_d> </enum_d>
<enum_e> </enum_e>
<enum_f> </enum_f>
<enum_g> </enum_g>
<enum_h> </enum_h>
<chron_i> </chron_i>
<chron_j> </chron_j>
<chron_k> </chron_k>
<chron_l> </chron_l>
<chron_m> </chron_m>
<break_indicator> </break_indicator>
<pattern_type> </pattern_type>
<linking_number> </linking_number>
<type_of_unit> </type_of_unit>
<issue_level_description>no.41 2018/2020</issue_level_description>
<receiving_operator>scdn4jv3</receiving_operator>
<process_type_name>Transit</process_type_name>
<process_type_code>TRANSIT</process_type_code>
<inventory_number> </inventory_number>
<inventory_price> </inventory_price>
<library_name>Library for International and Public Affairs</library_name>
<library_code>VKC</library_code>
<location_name>BOOKSTACKS</location_name>
<location_code>vkc-stk</location_code>
<alternative_call_number> </alternative_call_number>
<alternative_call_number_type> </alternative_call_number_type>
<storage_location_id> </storage_location_id>
<pages> </pages>
<pieces> </pieces>
<public_note> </public_note>
<fulfillment_note> </fulfillment_note>
<internal_note_1> </internal_note_1>
<internal_note_2> </internal_note_2>
<internal_note_3> </internal_note_3>
<statistics_note_1> </statistics_note_1>
<statistics_note_2> </statistics_note_2>
<statistics_note_3> </statistics_note_3>
<requested>true</requested>
<edition> </edition>
<imprint>London : HMSO, 1988-</imprint>
<language>eng</language>
<library_details>
<address>
<line1>University Park Campus</line1>
<line2>3518 Trousdale Parkway</line2>
<line3>VKC-B40</line3>
<line4> </line4>
<line5> </line5>
<city>Los Angeles</city>
<country_name>United States</country_name>
<country_code>USA</country_code>
<email> </email>
<phone>213-740-1749</phone>
<postal_code>90089-0048</postal_code>
<state>CA</state> </address> </library_details>
<parsed_call_number>
<call_no_1>HA</call_no_1>
<call_no_2>1123</call_no_2>
<call_no_3>.L625</call_no_3> </parsed_call_number>
<parsed_issue_level_description>
<issue_level_description_1>no.41</issue_level_description_1>
<issue_level_description_2>2018/2020</issue_level_description_2> </parsed_issue_level_description>
<title_abcnph>Key population and vital statistics. Local and health authority areas / Office of Population Censuses and Surveys.</title_abcnph>
<retention_reason> </retention_reason>
<retention_note> </retention_note>
<current_date>6/19/2023</current_date> </physical_item_display_for_printing> </section-01> </printout>

*** Settings ***

<spinelabel_settings>
<radio_comma>false</radio_comma>
<radio_decimalpoint>true</radio_decimalpoint>
<radio_unitcm>false</radio_unitcm>
<radio_unitinch>true</radio_unitinch>
<numud_repeatnum>1</numud_repeatnum>
<check_showtips>false</check_showtips>
<text_stationname>Station?</text_stationname>
<check_requireuser>false</check_requireuser>
<check_createtemp>false</check_createtemp>
<text_viadosAscii>12</text_viadosAscii>
<radio_useformfeed>false</radio_useformfeed>
<radio_labellength>true</radio_labellength>
<text_viadosnumlines>12</text_viadosnumlines>
<text_dosparam2></text_dosparam2>
<text_dosparam1></text_dosparam1>
<check_runhidden>false</check_runhidden>
<text_plnumtabs>1</text_plnumtabs>
<text_plnumcols>10</text_plnumcols>
<radio_dosplusetab>false</radio_dosplusetab>
<radio_useplcolspacing>true</radio_useplcolspacing>
<check_useviados>false</check_useviados>
<radio_portrait>true</radio_portrait>
<radio_landscape>false</radio_landscape>
<text_topmargin>0.4</text_topmargin>
<text_leftmargin>0.1</text_leftmargin>
<text_linespacing>0.2</text_linespacing>
<radio_uselaser>true</radio_uselaser>
<text_ftpmaxlines>8</text_ftpmaxlines>
<text_ftpmaxcharsperline>9</text_ftpmaxcharsperline>
<radio_useftp>false</radio_useftp>
<radio_usedesktop>false</radio_usedesktop>
<texo_ftppassword></texo_ftppassword>
<text_ftplogin></text_ftplogin>
<text_ftpipaddress></text_ftpipaddress>
<text_ftpfontsize>12</text_ftpfontsize>
<text_ftpfontnum>8</text_ftpfontnum>
<text_ftplinespacing>5</text_ftplinespacing>
<text_ftptop>4</text_ftptop>
<text_ftplmargin>2</text_ftplmargin>
<text_ftpcommands>M l fnt;gothic.ttf~cr~m m~cr~J~cr~H 100~cr~S l1;12,0,37,41,25~cr~O R~cr~F 8;gothic~cr~#LABELTEXT#~cr~A #COUNT#</text_ftpcommands>
<check_BCfontweight>false</check_BCfontweight>
<text_BCfontsize>12</text_BCfontsize>
<text_BCfontname>ALA BT Courier</text_BCfontname>
<numud_batchnum>1</numud_batchnum>
<text_lblgapheight>0.0</text_lblgapheight>
<text_lblgapwidth>0.0</text_lblgapwidth>
<text_lblheight>2.0</text_lblheight>
<text_lblwidth>1.0</text_lblwidth>
<text_lblcols>8</text_lblcols>
<text_lblrows>5</text_lblrows>
<check_fontweight>false</check_fontweight>
<text_fontsize>12</text_fontsize>
<text_fontname>ALA BT Courier</text_fontname>
<text_printername>libhp-cal-220n</text_printername>
<text_plmax4>0</text_plmax4>
<text_plmax3>0</text_plmax3>
<text_plmax2>0</text_plmax2>
<text_plmax1>0</text_plmax1>
<text_plmin4>0</text_plmin4>
<text_plmin3>0</text_plmin3>
<text_plmin2>0</text_plmin2>
<text_plmin1>0</text_plmin1>
<text_plsource4></text_plsource4>
<text_plsource3></text_plsource3>
<text_plsource2></text_plsource2>
<text_plsource1></text_plsource1>
<radio_SL6>false</radio_SL6>
<radio_SL4>false</radio_SL4>
<radio_plSLB>true</radio_plSLB>
<text_plLeftmargin>1.2</text_plLeftmargin>
<numud_pocketlabelcount>1</numud_pocketlabelcount>
<text_pldistance>0.0</text_pldistance>
<radio_SLCUSTOM>false</radio_SLCUSTOM>
<text_convertblankcntype>0</text_convertblankcntype>
<check_hidecutterdecimal>false</check_hidecutterdecimal>
<text_lctype>0,2</text_lctype>
<check_lcremoveafter>false</check_lcremoveafter>
<text_lcbreak></text_lcbreak>
<radio_lcotherbreakaft>false</radio_lcotherbreakaft>
<radio_lcotherbreakb4>false</radio_lcotherbreakb4>
<radio_lcothernobreak>true</radio_lcothernobreak>
<radio_lccutterspacebreak>true</radio_lccutterspacebreak>
<radio_lccutterspacenobreak>false</radio_lccutterspacenobreak>
<radio_lccutterbreak>true</radio_lccutterbreak>
<radio_lccutternobreak>false</radio_lccutternobreak>
<radio_lcdecbreak>false</radio_lcdecbreak>
<radio_lcdecbreakbefore>false</radio_lcdecbreakbefore>
<radio_lcdecnobreak>true</radio_lcdecnobreak>
<radio_lcnumbreak>true</radio_lcnumbreak>
<radio_lcnumnobreak>false</radio_lcnumnobreak>
<check_deweydecimalbreak>false</check_deweydecimalbreak>
<text_deweydigitstobreak>4</text_deweydigitstobreak>
<text_deweydigitsperline>3</text_deweydigitsperline>
<check_deweydigitsperline>false</check_deweydigitsperline>
<text_deweytype>1</text_deweytype>
<check_deweyremoveafter>false</check_deweyremoveafter>
<text_deweybreak></text_deweybreak>
<radio_deweycharbreakaft>false</radio_deweycharbreakaft>
<radio_deweycharbreakb4>false</radio_deweycharbreakb4>
<radio_deweycharnobreak>true</radio_deweycharnobreak>
<radio_deweyprefixbreakaft>true</radio_deweyprefixbreakaft>
<radio_deweyprefixnobreak>false</radio_deweyprefixnobreak>
<radio_deweycutterspacebreak>true</radio_deweycutterspacebreak>
<radio_deweycutterspacenobreak>false</radio_deweycutterspacenobreak>
<radio_deweydecbreakaft>false</radio_deweydecbreakaft>
<radio_deweydecbreakb4>false</radio_deweydecbreakb4>
<radio_deweydecnobreak>true</radio_deweydecnobreak>
<check_sudocremoveafter>false</check_sudocremoveafter>
<text_sudocbreak></text_sudocbreak>
<radio_sudoccharbreakaft>false</radio_sudoccharbreakaft>
<radio_sudoccharbreakb4>false</radio_sudoccharbreakb4>
<radio_sudoccharnobreak>true</radio_sudoccharnobreak>
<text_sudoctype>3</text_sudoctype>
<radio_sudocnobreakb4numerics>true</radio_sudocnobreakb4numerics>
<radio_sudocbreakb4numerics>false</radio_sudocbreakb4numerics>
<radio_sudocnobrkdecimal>true</radio_sudocnobrkdecimal>
<radio_sudocbrkdecimal>false</radio_sudocbrkdecimal>
<radio_sudocbrkb4colon>true</radio_sudocbrkb4colon>
<radio_sudocbrkaftercolon>false</radio_sudocbrkaftercolon>
<radio_sudoccolonnobrk>false</radio_sudoccolonnobrk>
<radio_sudocdashnobrk>false</radio_sudocdashnobrk>
<radio_sudocdashbrk>true</radio_sudocdashbrk>
<radio_sudocslashnobrk>false</radio_sudocslashnobrk>
<radio_sudocslashbrk>true</radio_sudocslashbrk>
<text_othertype>4,7,8</text_othertype>
<check_otherremoveafter>false</check_otherremoveafter>
<radio_otherfirstspacebrk>false</radio_otherfirstspacebrk>
<radio_othernumbrkafter>false</radio_othernumbrkafter>
<radio_othernumbrkb4>false</radio_othernumbrkb4>
<radio_othernumnobrk>true</radio_othernumnobrk>
<radio_otherbrkafter>false</radio_otherbrkafter>
<radio_otherbrkb4>false</radio_otherbrkb4>
<radio_othernolistbrk>true</radio_othernolistbrk>
<text_otherlist></text_otherlist>
<radio_otherallspacebrk>true</radio_otherallspacebrk>
<radio_othernospacebrk>false</radio_othernospacebrk>
<check_holdingsspacebreak>false</check_holdingsspacebreak>
<radio_issuebrkafter>false</radio_issuebrkafter>
<radio_issuebrkb4>false</radio_issuebrkb4>
<radio_issuenolistbrk>true</radio_issuenolistbrk>
<check_issueremoveother>false</check_issueremoveother>
<text_issuelist></text_issuelist>
<check_issuebreakparen>true</check_issuebreakparen>
<check_protectcolon>true</check_protectcolon>
<check_issuebreakcolon>true</check_issuebreakcolon>
<check_pocketLabels>false</check_pocketLabels>
<text_nonflagwrapwidth>1.0</text_nonflagwrapwidth>
<text_flagwrapwidth>2.4</text_flagwrapwidth>
<text_nonflagdefaults>0.4|0.1|0.2|1.0|0.0|2.0|0.0|5|8|8|9|true|<library_code>~cr~%<call_number>~cr~<issue_level_description>~cr~</text_nonflagdefaults>
<text_flagdefaults>0.5|0.1|0.2|2.7|0.0|7.0|0.0|1|4|30|50|false|!<barcode>~cr~~<location_name>~cr~%<call_number>~cr~#<issue_level_description>~cr~~=<title></text_flagdefaults>
<text_inothersource></text_inothersource>
<check_includeother>false</check_includeother>
<check_includeholdings>true</check_includeholdings>
<text_parsingsource><library_code></text_parsingsource>
<radio_useexlibrisparsing>false</radio_useexlibrisparsing>
<text_callnumsource><call_number></text_callnumsource>
<text_lcissuedescsource><issue_level_description></text_lcissuedescsource>
<check_flagslips>false</check_flagslips>
<radio_spine>false</radio_spine>
<radio_currper>true</radio_currper>
<text_custom><library_code>~cr~%<call_number>~cr~<issue_level_description>~cr~</text_custom>
<text_suppress3></text_suppress3>
<text_suppress2></text_suppress2>
<text_suppress1>0</text_suppress1>
<text_spinedefaults>0.1|0.1|0.2|1.0|0.0|2.0|0.0|5|8|7|9|true|</text_spinedefaults>
<text_pocketdefaults>0.4|0.1|0.2|1.0|0.0|2.0|0.0|5|8|8|9|true|<call_number>~cr~<issue_level_description>~cr~<current_date>~cr~<library_name>~cr~<location_name></text_pocketdefaults>
<radio_usesystem>false</radio_usesystem>
<radio_useLocal>true</radio_useLocal>
<text_abovelabeltexturl></text_abovelabeltexturl>
<text_locsource><location_name></text_locsource>
<text_libsource><library_name></text_libsource>
<check_xmlwarning>false</check_xmlwarning>
<chk_includesettings>false</chk_includesettings>
<text_restfulmethod>/almaws/v1/items?view=label&item_barcode={item_barcode}</text_restfulmethod>
<texo_restfulapikey>f<sui2hu$w's!!rs%w#tp&"u#$"!))$rw'!"</texo_restfulapikey>
<text_restfulalmaurl> https://api-na.hosted.exlibrisgroup.com</text_restfulalmaurl>
<radio_useRESTful>true</radio_useRESTful>
<texo_updatepath>b}6$%pcr?sr?tud+)!)!>Vtewx}t>vte.wx}t,</texo_updatepath>
<check_logedits>false</check_logedits>
<text_monitorfolder>\\mongo.usc.edu\rfolders\dnava\Desktop\</text_monitorfolder>
<radio_review>true</radio_review>
<radio_autoprint>false</radio_autoprint>
</spinelabel_settings>

Daniela Nava
Manager of Database Management & Preparations Section
University of Southern California
University Libraries-Technical Services
3434 South Grand Avenue, CAL-220-22
University Park Campus, MC-2810
Los Angeles, California 90089-2810
(213) 821-1715

________________________________

**Comment by mgobat** [comment]
@dncal213, do you have a myLabels.txt file in the SpineOMatic application directory? This file contains your defined label prefixes. You can edit he file manually or use the "Label Prefix" tab to edit it.

In the example XML you sent, assuming you have <library_name> set as the "Library source" and <location_name> set as the "Location source" on your "Label Prefixes" tab, you might have something like this in your myLabels.txt file:
`Library for International and Public Affairs+BOOKSTACKS=IPA STAX`

This should result in "IPA STAX" being printed on the label before any other elements.

See the documentation here:  https://github.com/ExLibrisGroup/SpineOMatic/wiki/Setup-Panels#label-prefixes-panel

**Comment by mgobat** [comment]
@dncal213. any update on your label prefix printing? Thanks.

**Comment by dncal213** [comment]
No, sorry still trying to figure out the how

Daniela Nava
Manager of Database Management & Preparations Section
University of Southern California
University Libraries-Technical Services
3434 South Grand Avenue, CAL-220-22
University Park Campus, MC-2810
Los Angeles, California 90089-2810
(213) 821-1715

________________________________

**Comment by mgobat** [comment]
@dncal213, ok, let's try to figure this out.

Looking at your XML example earlier, in your XML response after scanning an item you have
`<library_name>Library for International and Public Affairs</library_name>
<location_name>BOOKSTACKS</location_name>`

In this case, your "Label Prefixes" tab could look like this:

<img width="263" alt="label-prefixes" src="https://github.com/ExLibrisGroup/SpineOMatic/assets/45852490/96c6f71b-0465-4015-b1fc-202f18d5000a">

You must be sure that the library name and location name that you include match exactly what is in your XML for the items you scan. And I just put "IPX STAX" as an example of the prefix to use for demo purposes. 

Here's what an example of what it would look like after you scan a barcode:
<img width="374" alt="prefix-example" src="https://github.com/ExLibrisGroup/SpineOMatic/assets/45852490/20e31f94-c84e-492f-b2cf-3a8690d4f403">

**Comment by dncal213** [comment]
Thank you for the help. Sorry I have not had time to respond. This is one reason I continue to just change the label before printing but if I can figure out how to scan in with the correct library name, it would be a plus!
Library for International and Public Affairs+BOOKSTACKS=LIPA this is what I have for one library. The label should read LIPA but it continues to read the old VKC label.

Daniela Nava
Manager of Database Management & Preparations Section
University of Southern California
University Libraries-Technical Services
3434 South Grand Avenue, CAL-220-22
University Park Campus, MC-2810
Los Angeles, California 90089-2810
(213) 821-1715

________________________________

**Comment by mgobat** [comment]
@dncal213, I'm puzzled here. 
So your myLabelText.txt file only contains `Library for International and Public Affairs+BOOKSTACKS=LIPA`.

On your "Label Prefixes" tab, your "Library source" is set to `<library_name>` and your "Location source" is set to `<location_name>`.

And when you scan in the item with barcode 31275058410417, you don't get "LIPA" at the top of the label?

**Comment by dncal213** [comment]
No I do not, I need to make the change before sending it through

**Comment by mgobat** [comment]
@dncal213, does your institution permit Microsoft Teams sessions? If so, could we set one up so you could share your screen while using SpineOMatic? Maybe that would help me figure out what is going on. Thanks.

**Comment by CarolineReul** [comment]
In case this helps anyone, I was having the same problems until I noticed the "Load" button in the bottom right corner. If you click on it, it will load the prestamps you entered (as directed above) and then they will print on the spine labels.

**Comment by dncal213** [comment]
Under Call Number Format XML Sources if you input a + in front of <library_name>
like so +<library_name>
That worked for me.
Of course you need to set up the label prefixes first
