### ISSUE TITLE
Batch print only printing one label?

### ISSUE THREAD

**Issue by UNFLibSys** [ExLibrisGroup/SpineOMatic#61]
Cannot seem to figure out what's going wrong here and other guides online sound like they haven't encountered this issue before. I have 17 spine labels in a batch (Batch # 1) and I am in Batch Print mode. The app recognizes that there are 17 entries. However, when I go to preview/print, only one label will show up. I tried making another batch and found the same issue. I can go into single label printing and do them one at a time, but would prefer to use the batch print if I can figure it out. As you can see in the pictures below, even if I zoom out to 3-4 pages, etc., the print preview still only shows 1 label. Needless to say, it will only print the one label if I tell it to print the batch...

The app is up to date. Any advice?

![batch print](https://github.com/ExLibrisGroup/SpineOMatic/assets/138798639/335916f6-d620-4d37-9c55-76ec09c870c9)
![print prev](https://github.com/ExLibrisGroup/SpineOMatic/assets/138798639/bc85db99-fc04-4201-b2d6-4889fba84835)

**Comment by mgobat** [comment]
@UNFLibSys, I tried to replicate the problem, but couldn't. Of course, I don't have the printer you are using. May I suggest changing the printer to something else, like "Microsoft Print to PDF", to see if the printer is causing the issue? 

Here's a screenshot of my test:
![batchprint](https://github.com/ExLibrisGroup/SpineOMatic/assets/45852490/9c416937-8495-4ffd-bad7-5540e6be0456)

**Comment by UNFLibSys** [comment]
@mgobat I think it must be the printer then, because when I switched to Print to PDF all the labels showed up. Suppose I'll have to dig around in printer settings to see what I can discover. Thanks so much for reaching out, I really appreciate your help!

**Comment by mgobat** [comment]
@UNFLibSys, good luck!

**Comment by mgobat** [comment]
@UNFLibSys, just check in. Any better results?

**Comment by UNFLibSys** [comment]
@mgobat You are sweet to check in on us, thank you. :) We were able to resolve the problem! Like you suggested, it did seem to be something with the printer itself. We couldn't get it to print batches for whatever reason, but we are able to print the labels individually with no issue now that we've done some fiddling around with the app.

**Comment by mgobat** [comment]
@UNFLibSys, glad you have had some success. I'll close this issue.
