### ISSUE TITLE
Issue with program not using my font settings

### ISSUE THREAD

**Issue by sethmisk** [ExLibrisGroup/SpineOMatic#64]
I'm running SpineOMatic 7.0 on Windows 10 Enterprise edition.

I'm trying to print labels with the font set to bold, but the text that appears in the preview area (and on the label when it's printed) isn't bold, even though I have the "bold" option checked in my printing preferences and have saved them. I've tried restarting the program and the computer and it hasn't fixed the issue.

![Screenshot 2023-09-22 093107](https://github.com/ExLibrisGroup/SpineOMatic/assets/145783691/f905fc41-16f9-4c50-995f-576553bc38e7)

**Comment by mgobat** [comment]
Hi @sethmisk...

I think the effectiveness of the bolding depends on the font you are using. Here's an example of regular vs bold using the "Arial" font:

<img width="299" alt="regVbold" src="https://github.com/ExLibrisGroup/SpineOMatic/assets/45852490/c781783d-8981-462e-a80d-6df711afa458">

Could you please try a different font?

Thank you.

**Comment by mgobat** [comment]
@sethmisk, please try using the latest version available here:  
https://github.com/ExLibrisGroup/SpineOMatic/releases/tag/v8.1.2

Note that versions post 7.0 require a newer version of the .NET framework available here:
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by mgobat** [comment]
No response from reporter; assumed no longer an issue.
