### ISSUE TITLE
Adding label prefixes from file?

### ISSUE THREAD

**Issue by sethmisk** [ExLibrisGroup/SpineOMatic#66]
I see in the "Label Prefixes" settings tab there's a way to import prefixes from a file rather than entering them manually, but I can't find anything in the wiki about how to do this. We've had to uninstall and reinstall the program and it wiped out all of our settings including the label prefixes, and I want to make a file we can import so we don't have to re-enter them manually next time.

**Comment by mgobat** [comment]
If you are using a local file for the label prefixes, you first create the file using the application on one workstation. Then you can copy the myLabelText.txt file from the original workstation to the others.

1. On the "Label Prefixes" tab, select the "Use local file" radio button.
2. Create your label prefixes.
3. Click "Save Changes". The file myLabelText.txt will be created on the workstation in the folder containing the application.
4. Copy the file to the other workstations.
5. Ensure the "Use local file" radio button is selected on the workstations to which you copy the file.

**Comment by mgobat** [comment]
@sethmisk, just checking if you saw my reply to this issue last week. If so, did you get a chance to try it?  Thank you.
