### ISSUE TITLE
Printing Custom Pocket Labels

### ISSUE THREAD

**Issue by ssilver2024** [ExLibrisGroup/SpineOMatic#68]
Hello,

Thanks for developing this program!

The custom pocket label creator seems to populate the labels in a batch without issue.  But, when I click to review/print the labels, the preview is blank.  Consequently the printed labels are blank.

Standard spine labels preview and print without issues.

What am I missing?
![SpineOMatic - pocket labels](https://github.com/ExLibrisGroup/SpineOMatic/assets/170346155/af6f3816-c5dd-4c8a-91e0-9886faff5558)

Thank you!

**Comment by mgobat** [comment]
@ssilver2024, could you add a screenshot of your "Call Number Format" tab, please?

**Comment by mgobat** [comment]
@ssilver2024, it looks like your left margin may be the problem if it is in fact "025". Is it missing a decimal somewhere?

**Comment by ssilver2024** [comment]
I added the decimal and it is working!  Thank you @mgobat!

**Comment by mgobat** [comment]
@ssilver2024, great!
