### ISSUE TITLE
Barcode Printing Issues

### ISSUE THREAD

**Issue by kelseygeller** [ExLibrisGroup/SpineOMatic#69]
We're having some issues when printing barcodes on our labels. 

1) For some reason, the written-out barcode is appearing on top of the barcode itself, creating unattractive gibberish (see 1st image). This does not happen when the barcode font is smaller, but our scanners won't scan it at that size (See 2nd image).

![gibberish barcode](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/006b0d5a-4859-421a-80d2-5acb6be4d823)

![small barcode](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/f4f54221-0ae6-4cbe-8af4-ce155fc3ff43)

2) The barcode on the above label is TCU-000014, but when the printed barcode is scanned, it's returning as TCU/M00014, and I'm not sure why. Is this an issue with the font?

3) Our labels made on our old system looked like this with the barcode centered in the label. Is this possible to replicate using the desktop version of Spineomatic? I'm not currently seeing a way to do so.

![old barcode](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/57e5c4b2-7a6c-47c5-bd3a-dfb2cc60699a)

Our settings currently look like this (with an exception being the barcode font size changed to 12 and line spacing to .18)

![settings](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/68ceca3c-cc39-4e7d-b31e-6ca64d887ee4)

[My library and I are new to Spineomatic, so please excuse any incorrect terminology or ignorance on my part.]

**Comment by mgobat** [comment]
@kelseygeller, please first try upgrading to the latest version, 8.1.2 (https://github.com/ExLibrisGroup/SpineOMatic/releases/download/v8.1.2/SpineLabeler.exe).

If the problem persists, please add a screenshot of your "Call Number Format" tab, and then a screenshot of any relevant "Tweak & Test" settings on the "Call Number Format" tab.

Thanks.

**Comment by kelseygeller** [comment]
@mgobat Thank you for the heads up about the update -- it didn't solve the problem, but I have done so now. Here's the current Print Setup, Call Number Format, and Tweak & Test pages. 

![callnumberformat0711](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/15e7d66c-602c-42e2-9c61-ffc7a7456145)
![printsetup0711](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/a61f541e-15fd-4462-bdb2-2592c8918d1e)
![tweaks0711](https://github.com/ExLibrisGroup/SpineOMatic/assets/172410724/9837276a-80d1-4e1e-b07a-e9941659fb65)

**Comment by kelseygeller** [comment]
I may have made things worse somehow? I downloaded the Free 3 of 9 font as recommended to try out, and while the barcode doesn't look jumbled anymore, it's too small, and now the margin spacing is entirely off despite not making any changes there. Unfortunately now, when I use the original font and margin settings, the new off spacing is printing instead. 

![bad spacing](https://github.com/user-attachments/assets/375b09e2-a868-4b5c-aefa-7ce68f890329)

**Comment by mgobat** [comment]
@kelseygeller, still looking into your font issues. Thanks for trying the Barcode 3 of 9 font. I'm having the same issues with that font and the Carolina Barcode font you originally were using.

The barcode cannot be centered in the SpineOMatic WIndows application, but it can be centered using the Alma Cloud App version.

**Comment by kelseygeller** [comment]
@mgobat I appreciate your help! And thank you for the note on centering -- that's what I assumed, but good to know for certain.

**Comment by mgobat** [comment]
@kelseygeller, you may wish to consider posting to the Alma listserv to learn of which fonts have been successful for other Alma sites. 

I'm having success with this barcode 3 of 9 font:  https://free-barcode.com/howto/Barcode-font.asp
I was able to generate a label, and my phone scanner correctly scanned its value.

**Comment by kelseygeller** [comment]
That barcode font is actually working well and scanning well for us too. I think I've got the font size and everything where we want it, but the only issue now is the margins on the label. We're still having the issue where everything is suddenly pushed to the right and further down, causing the printer to put out a second empty label every time we print. It being pushed to the right isn't an issue really, but it needs to come up so that it doesn't go onto the next label. I have both the top and left margins set to 0 and the line spacing still to 1.8, but it's still an issue. Is there something I can do to move it up?

![almostthere](https://github.com/user-attachments/assets/de72bd29-39fd-4ef9-a3b0-cfb72a6a2304)

**Comment by mgobat** [comment]
@kelseygeller, a printer driver may have its own properties you could tweak to see if anything there helps. Another option, though this might cause more issues with subsequent labels, is to set the top margin to a negative value. I don't have a label printer to test with, but printing to a PDF with a negative top margin did shift the top position of the generated label.

**Comment by kelseygeller** [comment]
@mgobat You were totally right -- the label size on the printing properties was off. I've got this beautiful label, and we're good to go! Thanks again so much for your help!

![Yay!](https://github.com/user-attachments/assets/9ddfc130-77d2-4416-8f9b-723de22e8730)

**Comment by mgobat** [comment]
@kelseygeller, glad you have success!
