### ISSUE TITLE
Unhandled exception 8.1.3

### ISSUE THREAD

**Issue by alainaecon** [ExLibrisGroup/SpineOMatic#71]
We are getting the same error message as Issue #70, even after installing 8.1.3. I have included a screenshot of the error message. 
![Screenshot 2024-08-27 113417](https://github.com/user-attachments/assets/466bcf5a-5c9b-4cbf-8152-5a242703bcf9)

**Comment by mgobat** [comment]
@alainaecon, please click the "Details" button and provide a screenshot of what is displayed. Thanks.

**Comment by khart20** [comment]
Note that 8.1.2 is working on our Windows 10 PCs, but this error is showing on our Windows 11 PCs.

**Comment by mgobat** [comment]
@alainaecon, @khart20. Is this happening with batch print preview as reported in issue #70, or is it a different workflow?  Thanks.

**Comment by khart20** [comment]
@mgobat We do not use batch print.   This is when we scan a single barcode and the XML is returned, as we can see it in the Current XML tab, but this error pops up and if we continue it does not process the XML into the preview.

**Comment by alainaecon** [comment]
This is the message under "details". I copied and pasted the message instead of screenshots due to its length. : 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Argument 'Length' must be greater or equal to zero.
   at Microsoft.VisualBasic.Strings.Mid(String str, Int32 Start, Int32 Length)
   at SpineLabeler.Form1.aboveCall(String libname, String liblocation)
   at SpineLabeler.Form1.printCallNum()
   at SpineLabeler.Form1.getBarcodeFile()
   at SpineLabeler.Form1.callAlma()
   at SpineLabeler.Form1.InputBox_KeyPress(Object sender, KeyPressEventArgs e)
   at System.Windows.Forms.Control.OnKeyPress(KeyPressEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SpineLabeler
    Assembly Version: 8.1.3.0
    Win32 Version: 8.1.3.0
    CodeBase: file:///C:/Spine-O-Matic%208.1.3/SpineLabeler.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System

**Comment by mgobat** [comment]
@alainaecon, @khart20. So that I understand all circumstances with the problem, let me summarize.

- You are using a "Printer type" of "Single label desktop" (Set on the "Print Setup" tab).
- You scan in a single barcode on Windows 10 and the label prints fine.
- You scan in the same single barcode on Windows 11, and you get the 'unhandled exception' error with both version 8.1.2 and 8.1.3.
- Ignoring the error on Windows 11, you can click the "Current XML" tab and see the XML returned for the scanned in barcode.

Please confirm I have the problem steps correct. If I do, please copy the XML from the "Current XML" tab (make sure the "include settings" checkbox is checked) after you have scanned in the barcode and gotten the "unhandled exception" error, and paste it into a text file. Please remove the restfulapikey entry in the XML before posting here. You can then add the file to a comment by dragging/dropping the file.

Thank you.

**Comment by alainaecon** [comment]
- Correct. 
- Correct. 
- Correct. 
- Correct. 
[spine-o-matic xml.txt](https://github.com/user-attachments/files/16783636/spine-o-matic.xml.txt)

Let me know if you need any more information, thank you so much!

**Comment by khart20** [comment]
If it helps.  Here is a comparison/diff view of that XML output between 8.1.3 and our working 8.1.2 for same item barcode. 
<img width="710" alt="Diff813to812" src="https://github.com/user-attachments/assets/b19c87e0-705f-43d3-b151-9af988b813a8">

**Comment by alainaecon** [comment]
The Windows 11 computer has version 4.8 of the .Net Framework. I uninstalled and reinstalled "Microsoft Print to PDF", then changed the printer in SpineOMatic, and I still get the same error message as before when I scan a barcode.

**Comment by mgobat** [comment]
Thanks for running that test, @alainaecon.

**Comment by mgobat** [comment]
@alainaecon, @khart20, I'm trying to isolate where the problem may be in the code. Based on what I'm seeing, I'm assuming you have label prefixes defined on the "Label Prefixes" tab. If that is correct, can you confirm that the problem does not happen if you delete the label prefixes defined on the "Label Prefixes" tab? If the problem does not still occur, then try recreating your label prefixes and test again.

**Comment by alainaecon** [comment]
We isolated our label prefixes and were able to discover the issue! We are undergoing a library renovation and had to create some new label prefixes for our temporary location, and there was an error in one of those prefixes. Ultimately has nothing to do with Windows 11, just a coincidence that the Windows 10 computer did not have those new label prefixes added yet. 

Thank you so much for your help in resolving this!

**Comment by mgobat** [comment]
That's great, @alainaecon. Sorry I didn't think of that first.

**Comment by khart20** [comment]
@mgobat Mark Thank you for your help!
