### ISSUE TITLE
SpineOMatic Printing Gibberish

### ISSUE THREAD

**Issue by BFoley-MIDD** [ExLibrisGroup/SpineOMatic#75]
Problem is very similar to  **Text in Labels is gibberish #28.** 
After about 2 hour I manged to get our Zebra label printer to print out labels correctly after a reset of the ZDesigner ZT230 hardware -- but within 1 day it went back to printing the gibberish seen in the photo.
PrCpog407
4wxxhhjjP3
85hu1ijPlU2

You get the idea.
Help? 
Brian Foley.
![SpineOMatic-GIBBERISH](https://github.com/user-attachments/assets/04729f69-98aa-4b11-8185-bdd6c2a6698d)
![SpineOMatic-GIBBERISH](https://github.com/user-attachments/assets/7cbe338c-3428-450a-8851-c6d80839fdae)

**Comment by mgobat** [comment]
Hi @BFoley-MIDD. Just want to confirm this is the Windows SpineOMatic App and not the SpineOMatic Cloud App. Thanks.

**Comment by mgobat** [comment]
@BFoley-MIDD, does the printer always start printing correctly again once you reset it?

**Comment by BFoley-MIDD** [comment]
Here’s an update on my work with getting SpineOMatic to work with ZEBRA ZT230 label printer.
* I'm using the SpineOMatic Software. Not the web-interface. 

**Foreword:** 
I have installed the SpineOMatic software on 5 computers (my own Win11 desktop computer, Win10 laptop, a Win10 shared desktop, a Win11 desktop & a Win11 laptop) and none of them have functioned correctly except for the Windows 10 desktop computer.  The Win10 Desktop already had its ZEBRA ZM400 printer installed.  So I just installed SpineOMatic.  This system worked right-off-the-bat.  
All the other computers I had to install the ZEBRA ZM400 and/or ZT230 printer drivers.

- I tried resetting the ZEBRA ZT230 per the instructions on the ZEBRA website, but this did naught to remedy the issue.  The labels still printed out gibberish. 
- I worked a for a while longer adjusting settings in the SpineOMatic application but still nothing altered the output.
- I then took the opportunity to see if I could get the Win10 ZEBRA ZM400 label printer to work with my test Win11 laptop (this is the setup that is actually printing labels correctly ) -- hoping that this would give me some benchmark to go by and some insight to where the issue(s) are.
- Needless to say, after about 2 hours of trying to get The ZM400 to print correctly; it also failed on my Win11 laptop, yielding the same garbage printouts.
- This at least enlightened me that its most likely ‘not’ the printer itself – the issue probably resides with the printer drivers working with the application itself. ( just a hunch )

**Current Status: **
I’m going to try to reset the ZEBRA ZT230 printer again and see what comes of it.  I was successful ‘once’ with Win11 Desktop installation of SpineOMatic after the printer was reset – though it returned to its typical non-printing status the next day.

**Question/Wondering: ** Is there chance that the ZEBRA drivers need to be installed prior to even attaching ZEBRA printer to work correctly - and/or - the SpineOMatic MUST be installed after the ZEBRA drivers?  
Would that really cause all these issues? 

I'm going to see what the person did with the Win10 desktop that has SpineOMatic working with their ZEBRA ZM400.   Not sure what magic they used -- but these are just label printers with their associated software driver installers.  I've done printer & label printer installations for years & not run into this kind of conundrum.

**Comment by mgobat** [comment]
@BFoley-MIDD, agree that this is a crazy conundrum. The SpineOMatic Windows application is just a simple Windows binary; it does not install anything, does not update Windows, nor does it touch the Windows registry. All of its settings are stored in the settings.som file. It simply relies on the selected printer driver. The order of setup shouldn't matter, though the printer driver needs to be installed before it can be selected in SpineOMatic. Unfortunately, we don't have a ZM400 printer to try to replicate/diagnose this problem.

We can dig into the code some more to see if anything looks questionable. Does the problem happen with both single label and batch printing?

**Comment by BFoley-MIDD** [comment]
Just single at this point. 
I've pulled an image from both the OptiPlex 7060 & 7000 that have SpineOMatic & ZEBRA ZM400 working and going to push the images onto another like computer ( _I can't muck up their working systems or 😡librarians_ ) .
On these computers that I've pushed the working image I'm going to see if I can't get the ZT230 drivers working.  
Yeah ... kinda driving me nuts.

**Comment by BFoley-MIDD** [comment]
I guess this ZT230 has been working using the Sierra system for years.  Not sure if that has anything to do with it.

**Comment by BFoley-MIDD** [comment]
I made some major headway here!  I was working with a clean install w/ both Win10 & Win11.  Installed the ZEBRA ZM400 drivers and they both printed gibberish.
I examined the 2 Win10 stations that are currently working with the ZM400 and I noticed that their ZEBRA _Printer Preferences & Printing Properties_ settings were significantly different.  
I noticed on the working systems that the ZEBRA printers were using a driver called "**Generic / Text Only**" and not ZEBRA.
![ZEBRA PrintPrefs - GOOD 1](https://github.com/user-attachments/assets/85eafac6-3b5c-42fc-b00f-206c59b85c3d)
![ZEBRA PrintPrefs - GOOD](https://github.com/user-attachments/assets/bb0d3429-1684-426c-8cbb-1253e90409d6)
The config settings after you install the ZEBRA drivers that **_don't_** work yield ZEBRA Printing Preference window that looks like this :
![ZEBRA - PrintPref - BAD](https://github.com/user-attachments/assets/78ef505e-a4c2-495d-b4ac-2c52307fb180)
Switching the driver to "**Generic / Text Only**" from the initial driver [ _ZEBRA something_ ] yields a correct label printout from SpineOMatic!! 
This worked with the ZM400 -- going to try the ZT230 next.
_* NOTE when I switch drivers, the printer was automatically renamed to something along the lines of "Generic Text".  I just renamed it to **ZEBRA "Generic Text**" and it was fine._

**Comment by mgobat** [comment]
Great progress, @BFoley-MIDD. You may wish to share this information on Alma-L.

**Comment by BFoley-MIDD** [comment]
I'm going to verify that this is indeed a fix for the issue.
If it is ... I'll share the info.
Wish me luck!
BF.

**Comment by BFoley-MIDD** [comment]
_O frabjous day! Callooh! Callay!_”  It worked!  Changing the installed ZEBRA label printer drivers to '**GENERIC / Text only**' got the ZEBRA ZT230 to print out a label correctly!! 
How do I share this information on Alma-L.?

**Comment by mgobat** [comment]
Nice job tracking down the issues, @BFoley-MIDD! Here's a [link](https://el-una.org/about/mailing-lists/alma-mailing-lists/) with information about Alma-L.
